package api

import (
	"bufio"
	"context"
	"fmt"
	"log/slog"
	"net"
	"net/http"
	"strings"
	"time"

	"github.com/cogitatorai/cogitator/server/internal/auth"
	"github.com/cogitatorai/cogitator/server/internal/metrics"
	"github.com/cogitatorai/cogitator/server/internal/reqctx"
	"github.com/oklog/ulid/v2"
)

type requestCtxKey int

const (
	routeInfoKey requestCtxKey = iota
)

// RequestIDFromContext returns the per-request ULID generated by
// requestLogMiddleware, or "" when absent (e.g. unit tests that hit a
// handler directly).
func RequestIDFromContext(ctx context.Context) string {
	return reqctx.RequestID(ctx)
}

// routeInfo is planted in the request context by requestLogMiddleware and
// filled in by routeCaptureMiddleware after the mux has matched, because
// inner middlewares replace the request (WithContext) so pattern and user
// are invisible on the outer middleware's own *http.Request.
type routeInfo struct {
	pattern string
	userID  string
}

// logStatusWriter tracks status and hijacking for the request log.
// It forwards Hijack and Flush so WebSocket upgrades and streaming work.
type logStatusWriter struct {
	http.ResponseWriter
	status   int
	hijacked bool
}

func (w *logStatusWriter) WriteHeader(code int) {
	w.status = code
	w.ResponseWriter.WriteHeader(code)
}

func (w *logStatusWriter) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	hj, ok := w.ResponseWriter.(http.Hijacker)
	if !ok {
		return nil, nil, fmt.Errorf("underlying ResponseWriter does not implement http.Hijacker")
	}
	conn, rw, err := hj.Hijack()
	if err == nil {
		w.hijacked = true
		w.status = http.StatusSwitchingProtocols
	}
	return conn, rw, err
}

func (w *logStatusWriter) Flush() {
	if f, ok := w.ResponseWriter.(http.Flusher); ok {
		f.Flush()
	}
}

// requestLogMiddleware generates a ULID request ID (returned as X-Request-Id
// and stored in the context), logs every request, and records latency/status/
// route into the metrics ring. The query string is never logged: /ws carries
// the JWT in ?token=. Health probes and static assets log at debug to keep
// the info stream useful.
func requestLogMiddleware(ring *metrics.Ring) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			start := time.Now()
			id := ulid.Make().String()
			info := &routeInfo{}
			ctx := reqctx.WithRequestID(r.Context(), id)
			ctx = context.WithValue(ctx, routeInfoKey, info)
			w.Header().Set("X-Request-Id", id)

			sw := &logStatusWriter{ResponseWriter: w, status: http.StatusOK}
			next.ServeHTTP(sw, r.WithContext(ctx))

			duration := time.Since(start)
			route := info.pattern
			if route == "" {
				route = "unmatched"
			}

			// Hijacked connections (WebSocket) measure connection lifetime,
			// not request latency; keep them out of the latency ring.
			if ring != nil && !sw.hijacked {
				ring.Record(duration, sw.status, route)
			}

			level := slog.LevelInfo
			if r.URL.Path == "/api/health" || r.URL.Path == "/api/ready" ||
				(!strings.HasPrefix(r.URL.Path, "/api/") && r.URL.Path != "/ws") {
				level = slog.LevelDebug
			}
			attrs := []any{
				"request_id", id,
				"method", r.Method,
				"path", r.URL.Path,
				"route", route,
				"status", sw.status,
				"duration_ms", duration.Milliseconds(),
			}
			if info.userID != "" {
				attrs = append(attrs, "user_id", info.userID)
			}
			slog.Log(ctx, level, "http request", attrs...)
		})
	}
}

// routeCaptureMiddleware wraps the mux directly. After the mux runs it copies
// the matched pattern (set by ServeMux on this request) and the authenticated
// user into the routeInfo planted by requestLogMiddleware.
func routeCaptureMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		next.ServeHTTP(w, r)
		info, _ := r.Context().Value(routeInfoKey).(*routeInfo)
		if info == nil {
			return
		}
		info.pattern = r.Pattern
		if u, ok := auth.UserFromContext(r.Context()); ok {
			info.userID = u.ID
		}
	})
}
